// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: tx.proto

package contract

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction represents a request or action submitted to the network.
// THIS MUST MATCH lib.Transaction EXACTLY for signing — field numbers,
// types, and json tags must not be changed.
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	Msg           *any1.Any              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature     *Signature             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Time          uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Fee           uint64                 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Memo          string                 `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	NetworkId     uint64                 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	ChainId       uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"`       // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *any1.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// MessageSend is a standard transfer transaction
type MessageSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"`       // @gotags: json:"toAddress"
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// FeeParams defines minimum fees for each transaction type.
// Add Praxis fee fields starting at field 14 to avoid conflicts.
type FeeParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendFee       uint64                 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"` // @gotags: json:"sendFee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

// Signature holds the BLS12-381 public key and signature bytes
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MessageCreateMarket opens a new YES/NO prediction market.
// Fields 1–6 — do not reorder; frontend hand-encoder depends on this order.
type MessageCreateMarket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CreatorAddress   []byte                 `protobuf:"bytes,1,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"` // @gotags: json:"creatorAddress"
	Question         string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ResolverAddress  []byte                 `protobuf:"bytes,4,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolverAddress"`     // @gotags: json:"resolverAddress"
	ResolutionHeight uint64                 `protobuf:"varint,5,opt,name=resolution_height,json=resolutionHeight,proto3" json:"resolutionHeight"` // @gotags: json:"resolutionHeight"
	StakeAmount      uint64                 `protobuf:"varint,6,opt,name=stake_amount,json=stakeAmount,proto3" json:"stakeAmount"`                // @gotags: json:"stakeAmount"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageCreateMarket) Reset() {
	*x = MessageCreateMarket{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreateMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreateMarket) ProtoMessage() {}

func (x *MessageCreateMarket) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreateMarket.ProtoReflect.Descriptor instead.
func (*MessageCreateMarket) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageCreateMarket) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *MessageCreateMarket) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MessageCreateMarket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MessageCreateMarket) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *MessageCreateMarket) GetResolutionHeight() uint64 {
	if x != nil {
		return x.ResolutionHeight
	}
	return 0
}

func (x *MessageCreateMarket) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

// MessageSubmitPrediction places a stake on an outcome.
// outcome: 1 = YES, 2 = NO
type MessageSubmitPrediction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ForecasterAddress []byte                 `protobuf:"bytes,1,opt,name=forecaster_address,json=forecasterAddress,proto3" json:"forecasterAddress"` // @gotags: json:"forecasterAddress"
	MarketId          uint64                 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"marketId"`                           // @gotags: json:"marketId"
	Outcome           uint32                 `protobuf:"varint,3,opt,name=outcome,proto3" json:"outcome,omitempty"`                                             // 1 = YES, 2 = NO
	Amount            uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageSubmitPrediction) Reset() {
	*x = MessageSubmitPrediction{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubmitPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubmitPrediction) ProtoMessage() {}

func (x *MessageSubmitPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubmitPrediction.ProtoReflect.Descriptor instead.
func (*MessageSubmitPrediction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageSubmitPrediction) GetForecasterAddress() []byte {
	if x != nil {
		return x.ForecasterAddress
	}
	return nil
}

func (x *MessageSubmitPrediction) GetMarketId() uint64 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *MessageSubmitPrediction) GetOutcome() uint32 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *MessageSubmitPrediction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// MessageResolveMarket finalises a market with the winning outcome.
// winning_outcome: 1 = YES, 2 = NO
type MessageResolveMarket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolverAddress []byte                 `protobuf:"bytes,1,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolverAddress"` // @gotags: json:"resolverAddress"
	MarketId        uint64                 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"marketId"`                     // @gotags: json:"marketId"
	WinningOutcome  uint32                 `protobuf:"varint,3,opt,name=winning_outcome,json=winningOutcome,proto3" json:"winningOutcome"`   // @gotags: json:"winningOutcome"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageResolveMarket) Reset() {
	*x = MessageResolveMarket{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResolveMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResolveMarket) ProtoMessage() {}

func (x *MessageResolveMarket) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResolveMarket.ProtoReflect.Descriptor instead.
func (*MessageResolveMarket) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageResolveMarket) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *MessageResolveMarket) GetMarketId() uint64 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *MessageResolveMarket) GetWinningOutcome() uint32 {
	if x != nil {
		return x.WinningOutcome
	}
	return 0
}

// MessageClaimWinnings pays out a winner's stake and proportional winnings.
type MessageClaimWinnings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClaimerAddress []byte                 `protobuf:"bytes,1,opt,name=claimer_address,json=claimerAddress,proto3" json:"claimerAddress"` // @gotags: json:"claimerAddress"
	MarketId       uint64                 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"marketId"`                  // @gotags: json:"marketId"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageClaimWinnings) Reset() {
	*x = MessageClaimWinnings{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageClaimWinnings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageClaimWinnings) ProtoMessage() {}

func (x *MessageClaimWinnings) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageClaimWinnings.ProtoReflect.Descriptor instead.
func (*MessageClaimWinnings) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MessageClaimWinnings) GetClaimerAddress() []byte {
	if x != nil {
		return x.ClaimerAddress
	}
	return nil
}

func (x *MessageClaimWinnings) GetMarketId() uint64 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

// Market holds all on-chain state for one prediction market.
// status: 0 = open, 1 = resolved, 2 = cancelled
type Market struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorAddress   []byte                 `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"` // @gotags: json:"creatorAddress"
	Question         string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ResolverAddress  []byte                 `protobuf:"bytes,5,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolverAddress"`     // @gotags: json:"resolverAddress"
	ResolutionHeight uint64                 `protobuf:"varint,6,opt,name=resolution_height,json=resolutionHeight,proto3" json:"resolutionHeight"` // @gotags: json:"resolutionHeight"
	StakeAmount      uint64                 `protobuf:"varint,7,opt,name=stake_amount,json=stakeAmount,proto3" json:"stakeAmount"`                // @gotags: json:"stakeAmount"
	YesPool          uint64                 `protobuf:"varint,8,opt,name=yes_pool,json=yesPool,proto3" json:"yesPool"`                            // @gotags: json:"yesPool"
	NoPool           uint64                 `protobuf:"varint,9,opt,name=no_pool,json=noPool,proto3" json:"noPool"`                               // @gotags: json:"noPool"
	Status           uint32                 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                            // 0=open 1=resolved 2=cancelled
	WinningOutcome   uint32                 `protobuf:"varint,11,opt,name=winning_outcome,json=winningOutcome,proto3" json:"winningOutcome"`      // @gotags: json:"winningOutcome"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *Market) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Market) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *Market) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Market) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Market) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *Market) GetResolutionHeight() uint64 {
	if x != nil {
		return x.ResolutionHeight
	}
	return 0
}

func (x *Market) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *Market) GetYesPool() uint64 {
	if x != nil {
		return x.YesPool
	}
	return 0
}

func (x *Market) GetNoPool() uint64 {
	if x != nil {
		return x.NoPool
	}
	return 0
}

func (x *Market) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Market) GetWinningOutcome() uint32 {
	if x != nil {
		return x.WinningOutcome
	}
	return 0
}

// Prediction holds one forecaster's stake on a specific market.
type Prediction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ForecasterAddress []byte                 `protobuf:"bytes,1,opt,name=forecaster_address,json=forecasterAddress,proto3" json:"forecasterAddress"` // @gotags: json:"forecasterAddress"
	MarketId          uint64                 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"marketId"`                           // @gotags: json:"marketId"
	Outcome           uint32                 `protobuf:"varint,3,opt,name=outcome,proto3" json:"outcome,omitempty"`                                             // 1 = YES, 2 = NO
	Amount            uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Claimed           bool                   `protobuf:"varint,5,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *Prediction) GetForecasterAddress() []byte {
	if x != nil {
		return x.ForecasterAddress
	}
	return nil
}

func (x *Prediction) GetMarketId() uint64 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *Prediction) GetOutcome() uint32 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *Prediction) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Prediction) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

// MarketCounter is a singleton that tracks the next market ID.
// Key: KeyForMarketCounter() — only one instance exists in state.
type MarketCounter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketCounter) Reset() {
	*x = MarketCounter{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketCounter) ProtoMessage() {}

func (x *MarketCounter) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketCounter.ProtoReflect.Descriptor instead.
func (*MarketCounter) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MarketCounter) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"&\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xf7\x01\n" +
	"\x13MessageCreateMarket\x12'\n" +
	"\x0fcreator_address\x18\x01 \x01(\fR\x0ecreatorAddress\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10resolver_address\x18\x04 \x01(\fR\x0fresolverAddress\x12+\n" +
	"\x11resolution_height\x18\x05 \x01(\x04R\x10resolutionHeight\x12!\n" +
	"\fstake_amount\x18\x06 \x01(\x04R\vstakeAmount\"\x97\x01\n" +
	"\x17MessageSubmitPrediction\x12-\n" +
	"\x12forecaster_address\x18\x01 \x01(\fR\x11forecasterAddress\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\x04R\bmarketId\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\rR\aoutcome\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\"\x87\x01\n" +
	"\x14MessageResolveMarket\x12)\n" +
	"\x10resolver_address\x18\x01 \x01(\fR\x0fresolverAddress\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\x04R\bmarketId\x12'\n" +
	"\x0fwinning_outcome\x18\x03 \x01(\rR\x0ewinningOutcome\"\\\n" +
	"\x14MessageClaimWinnings\x12'\n" +
	"\x0fclaimer_address\x18\x01 \x01(\fR\x0eclaimerAddress\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\x04R\bmarketId\"\xef\x02\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fcreator_address\x18\x02 \x01(\fR\x0ecreatorAddress\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12)\n" +
	"\x10resolver_address\x18\x05 \x01(\fR\x0fresolverAddress\x12+\n" +
	"\x11resolution_height\x18\x06 \x01(\x04R\x10resolutionHeight\x12!\n" +
	"\fstake_amount\x18\a \x01(\x04R\vstakeAmount\x12\x19\n" +
	"\byes_pool\x18\b \x01(\x04R\ayesPool\x12\x17\n" +
	"\ano_pool\x18\t \x01(\x04R\x06noPool\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\rR\x06status\x12'\n" +
	"\x0fwinning_outcome\x18\v \x01(\rR\x0ewinningOutcome\"\xa4\x01\n" +
	"\n" +
	"Prediction\x12-\n" +
	"\x12forecaster_address\x18\x01 \x01(\fR\x11forecasterAddress\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\x04R\bmarketId\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\rR\aoutcome\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x18\n" +
	"\aclaimed\x18\x05 \x01(\bR\aclaimed\"%\n" +
	"\rMarketCounter\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05countB5Z3github.com/canopy-network/canopy/plugin/go/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tx_proto_goTypes = []any{
	(*Transaction)(nil),             // 0: types.Transaction
	(*MessageSend)(nil),             // 1: types.MessageSend
	(*FeeParams)(nil),               // 2: types.FeeParams
	(*Signature)(nil),               // 3: types.Signature
	(*MessageCreateMarket)(nil),     // 4: types.MessageCreateMarket
	(*MessageSubmitPrediction)(nil), // 5: types.MessageSubmitPrediction
	(*MessageResolveMarket)(nil),    // 6: types.MessageResolveMarket
	(*MessageClaimWinnings)(nil),    // 7: types.MessageClaimWinnings
	(*Market)(nil),                  // 8: types.Market
	(*Prediction)(nil),              // 9: types.Prediction
	(*MarketCounter)(nil),           // 10: types.MarketCounter
	(*any1.Any)(nil),                // 11: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	11, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	3,  // 1: types.Transaction.signature:type_name -> types.Signature
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
